//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBKUTUPHANEEntities1 : DbContext
    {
        public DBKUTUPHANEEntities1()
            : base("name=DBKUTUPHANEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_cezalar> Tbl_cezalar { get; set; }
        public virtual DbSet<Tbl_duyurular> Tbl_duyurular { get; set; }
        public virtual DbSet<Tbl_hakkımızda> Tbl_hakkımızda { get; set; }
        public virtual DbSet<Tbl_Hareket> Tbl_Hareket { get; set; }
        public virtual DbSet<Tbl_iletisim> Tbl_iletisim { get; set; }
        public virtual DbSet<Tbl_Kasa> Tbl_Kasa { get; set; }
        public virtual DbSet<Tbl_kategori> Tbl_kategori { get; set; }
        public virtual DbSet<Tbl_kitap> Tbl_kitap { get; set; }
        public virtual DbSet<Tbl_mesajlar> Tbl_mesajlar { get; set; }
        public virtual DbSet<Tbl_personel> Tbl_personel { get; set; }
        public virtual DbSet<Tbl_üyeler> Tbl_üyeler { get; set; }
        public virtual DbSet<Tbl_yazar> Tbl_yazar { get; set; }
    }
}
