//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Hareket
    {
        public int HareketID { get; set; }
        public Nullable<int> Üye { get; set; }
        public Nullable<byte> Personel { get; set; }
        public Nullable<System.DateTime> AlısTarih { get; set; }
        public Nullable<System.DateTime> İadeTarih { get; set; }
        public Nullable<System.DateTime> UyeGetirmeTarih { get; set; }
        public Nullable<bool> IslemDurum { get; set; }
        public Nullable<int> Kitap { get; set; }
    
        public virtual Tbl_kitap Tbl_kitap { get; set; }
        public virtual Tbl_personel Tbl_personel { get; set; }
        public virtual Tbl_üyeler Tbl_üyeler { get; set; }
    }
}
