//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_üyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_üyeler()
        {
            this.Tbl_cezalar = new HashSet<Tbl_cezalar>();
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public int ÜyeID { get; set; }
        public string ÜyeAd { get; set; }
        public string ÜyeSoyad { get; set; }
        public string ÜyeMail { get; set; }
        public string KullanıcıAd { get; set; }

        [StringLength(50, MinimumLength = 7, ErrorMessage = "Password must be between 7 and 50 characters.")]
        public string ÜyeSifre { get; set; }
        public string Foto { get; set; }
        public string Tel { get; set; }
        public string okul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_cezalar> Tbl_cezalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
    }
}
