//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_personel()
        {
            this.Tbl_Hareket = new HashSet<Tbl_Hareket>();
        }
    
        public byte PersonelID { get; set; }
        public string PersonelAdSoyad { get; set; }
        public string PersonelEmail { get; set; }

        [StringLength(50, MinimumLength = 7, ErrorMessage = "Password must be between 7 and 50 characters.")]
        public string PersonelPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Hareket> Tbl_Hareket { get; set; }
    }
}
